baseURL: "http://magentapuppy.me/"
title: MagentaBlog
paginate: 5
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

publishDir: "/mnt/ddf46e84-10c6-40fb-85b2-99f14e503946/selfhost/Magenta-blog-Public"

permalinks:
  posts: posts/:slug/

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: MagentaBlog
  description: "Magenta's personal site"
  keywords: [Blog, Portfolio, PaperMod, Magenta, Puppy, Static]
  author: Magenta
  # author: ["Me", "You"] # multiple authors
  images: 
  - profile-banner.png
  DateFormat: "2006, Janurary 2"
  timeZone: "Australia/Melbourne"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  enableEmoji: true
  ShowFullTextinRSS: true
  ShowPostNavLinks: true
  enableInlineShortcodes: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  editPost:
    URL: "https://github.com/MagentaPuppy/MagentaSite/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

  label:
    text: "Home"
  #  icon: /profile.png
  #  iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Magenta's Page
    subtitle: "Check out my cringe socials"
    imageUrl: "profile-picture.webp"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile picture
    buttons:
      - name: Posts
        url: posts
      - name: About Me
        url: posts/about_me/

#*I hope to never touch making a site ever again. gosh this was pain*

#editing on the go
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Theverymagenta"
    - name: youtube
      url: "https://www.youtube.com/channel/UCR4XbqQrv3Cq90P-h-QLDPA"
    - name: github
      url: "https://github.com/MagentaPuppy"

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/MagentaPuppy/MagentaSite/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 25
    - identifier: search
      name: search
      url: /search/
      weight: 30
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
